# default:cyan / root:red
if [ $UID -eq 0 ]; then
    PS1="\n\[\033[31m\]\u\[\033[00m\]:\[\033[01m\]\w\[\033[00m\]\\$ "
else
    PS1="\n\[\033[36m\]\u\[\033[00m\]:\[\033[01m\]\w\[\033[00m\]\\$ "
fi

# "-F":ディレクトリに"/"を表示 / "-G"でディレクトリを色表示
alias ls='ls -FG'
alias ll='ls -alFG'
alias la='ls -a'
